#
# Makefile for the Atheros ar9331 i2s driver
#
ath79-pcm-mbox-objs := ath79-pcm.o ath79-mbox.o

obj-$(CONFIG_AR9331_PCM)		+= ath79-pcm-mbox.o
obj-$(CONFIG_AR9331_I2S)		+= ath79-i2s.o
obj-$(CONFIG_AR9331_I2S_DEV)	+= dev-audio.o
obj-$(CONFIG_AR9331_qca-ap123-ak4430)		+= qca-ap123-ak4430.o
obj-$(CONFIG_AR9331_CARAMBOLA2)	+= mach-carambola2.o
